name: "🚀 Nova Funcionalidade"
description: Sugira uma nova funcionalidade ou melhoria no sistema.
title: "[Funcionalidade] Descreva brevemente a sugestão"
labels: ["Funcionalidade"]
body:
  - type: textarea
    id: descricao
    attributes:
      label: 🧠 Descrição
      description: Descreva claramente a funcionalidade desejada.

