name: "🚀 Nova Funcionalidade"
description: Sugira uma nova funcionalidade ou melhoria no sistema.
title: "[Funcionalidade] Descreva brevemente a sugestão"
labels: ["Funcionalidade"]
body:
  - type: textarea
    id: descricao
    attributes:
      label: 🧠 Descrição
      description: Descreva claramente a funcionalidade desejada.
      placeholder: Exemplo: Implementar autenticação via Google.
  - type: textarea
    id: comportamento_esperado
    attributes:
      label: ✅ Comportamento Esperado
      description: O que você espera que aconteça?
  - type: textarea
    id: contexto
    attributes:
      label: 📚 Contexto adicional
      description: Alguma informação extra, link ou referência?
